export const WORKOUTS = [
    {
        id: 0,
        day: 'Monday',
        category: 'Upper Body',
        mainTitle: 'Eccentric Workout Monday',
        name: 'Barbell Bench Press Variation',
        set: '3-4 sets @ 3-5 reps w/ final set AMRAP',
    },
    {
        id: 1,
        day: 'Monday',
        category: 'Upper Body',
        name: 'Dip',
        set: '3-4 sets x 8-20 reps',
    },
    {
        id: 2,
        day: 'Monday',
        category: 'Upper Body',
        name: 'Horizontal Pull Variation',
        set: '3-4 sets x 8-12 reps',
    },
    {
        id: 3,
        day: 'Monday',
        category: 'Upper Body',
        name: 'ISO Hold Y-W-T',
        set: '3-4 sets x 10-20 sec hold',
    },
    {
        id: 4,
        day: 'Monday',
        category: 'Upper Body',
        name: 'Dubbell Lateral Raise',
        set: '3-4 sets x 8-12 reps',
    },
    {
        id: 5,
        day: 'Monday',
        category: 'Upper Body',
        name: 'Bicep Curl',
        set: '3-4 sets x 8-12 reps',
    },
    {
        id: 6,
        day: 'Tuesday',
        category: 'Lower Body',
        mainTitle: 'Eccentric Low Body Tuesday',
        name: 'Partial Range Deadlift',
        set: '3-4 sets x 8-10 reps',
    },
    {
        id: 7,
        day: 'Tuesday',
        category: 'Lower Body',
        name: 'Romanian Deadlift',
        set: '3-4 sets x 8-10 reps',
    },
    {
        id: 8,
        day: 'Wednesday',
        category: 'Full Body',
        mainTitle: 'FullBody Wednesday',
        name: 'KB Swings',
        set: '3-4 sets x 10-12 reps'
    },
    {
        id: 9,
        day: "Wednesday",
        category: 'Full Body',
        name: 'KB reverse lunge',
        set: '3-4 sets x 8-10 reps',
    },
    {
        id: 10, 
        day: 'Thursday',
        category: 'Upper Body',
        mainTitle: 'Thursday Mass Volume Workout',
        name: 'Partial Range Barbell Bench Press',
        set: '3-4 sets x 8-10 reps',
    },
    {
        id: 11,
        day: 'Thursday',
        category: 'Upper Body',
        name: 'Cable Face Pull W/ External Rotation',
        set: '3-4 sets x 20 reps'
    },
    {
        id: 12,
        day: 'Friday',
        category: 'Lower Body',
        mainTitle: 'Friday Low Body Mass',
        name: 'Bulgarian Split Squat',
        set: '3-4 sets x 8-10 reps'
    },
    {
        id: 13,
        day: 'Friday',
        category: 'Lower Body',
        name: 'Front Squat',
        set: '5 sets w/ 2 reps (heavy weight)',
    },
];